project:
  type: book

book:
  title: "gsynth -- User Manual"
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - 01-gsynth.Rmd
    - 02-ife-mc.Rmd
    - 03-plots.Rmd
    - aa-changelog.Rmd
    - references.qmd

delete_merged_file: true

bibliography: references.bib

nocite: |
  @*

format:
  html:
    theme: cosmo
    df-print: paged
    code-fold: false
    code-tools: true
    code-link: true
    fig-format: svg

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    dev: svg
