# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

XXinv <- function(X) {
    .Call('gsynth_XXinv', PACKAGE = 'gsynth', X)
}

panel_est <- function(X, Y, MF) {
    .Call('gsynth_panel_est', PACKAGE = 'gsynth', X, Y, MF)
}

panel_beta <- function(X, xxinv, Y, F, L) {
    .Call('gsynth_panel_beta', PACKAGE = 'gsynth', X, xxinv, Y, F, L)
}

panel_factor <- function(E, r) {
    .Call('gsynth_panel_factor', PACKAGE = 'gsynth', E, r)
}

beta_iter <- function(X, xxinv, Y, r, tolerate, beta0) {
    .Call('gsynth_beta_iter', PACKAGE = 'gsynth', X, xxinv, Y, r, tolerate, beta0)
}

inter_fe <- function(Y, X, r, force, beta0, tol = 1e-5) {
    .Call('gsynth_inter_fe', PACKAGE = 'gsynth', Y, X, r, force, beta0, tol)
}

