# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastplm <- function(data, FE, FEcoefs = 0L) {
    .Call('_gsynth_fastplm', PACKAGE = 'gsynth', data, FE, FEcoefs)
}

fastplm_predict <- function(mu, FEvalues, FE, newx, beta) {
    .Call('_gsynth_fastplm_predict', PACKAGE = 'gsynth', mu, FEvalues, FE, newx, beta)
}

data_ub_adj <- function(I_data, data) {
    .Call('_gsynth_data_ub_adj', PACKAGE = 'gsynth', I_data, data)
}

XXinv <- function(X) {
    .Call('_gsynth_XXinv', PACKAGE = 'gsynth', X)
}

Y_demean <- function(Y, force) {
    .Call('_gsynth_Y_demean', PACKAGE = 'gsynth', Y, force)
}

fe_add <- function(alpha_Y, xi_Y, mu_Y, T, N, force) {
    .Call('_gsynth_fe_add', PACKAGE = 'gsynth', alpha_Y, xi_Y, mu_Y, T, N, force)
}

panel_est <- function(X, Y, MF) {
    .Call('_gsynth_panel_est', PACKAGE = 'gsynth', X, Y, MF)
}

panel_beta <- function(X, xxinv, Y, FE) {
    .Call('_gsynth_panel_beta', PACKAGE = 'gsynth', X, xxinv, Y, FE)
}

panel_factor <- function(E, r) {
    .Call('_gsynth_panel_factor', PACKAGE = 'gsynth', E, r)
}

panel_FE <- function(E, lambda) {
    .Call('_gsynth_panel_FE', PACKAGE = 'gsynth', E, lambda)
}

ife <- function(E, force, mc, r, lambda) {
    .Call('_gsynth_ife', PACKAGE = 'gsynth', E, force, mc, r, lambda)
}

fe_ad_iter <- function(Y, Y0, I, force, tolerate) {
    .Call('_gsynth_fe_ad_iter', PACKAGE = 'gsynth', Y, Y0, I, force, tolerate)
}

fe_ad_covar_iter <- function(XX, xxinv, Y, Y0, I, beta0, force, tolerate) {
    .Call('_gsynth_fe_ad_covar_iter', PACKAGE = 'gsynth', XX, xxinv, Y, Y0, I, beta0, force, tolerate)
}

fe_ad_inter_iter <- function(Y, Y0, I, force, mc, r, lambda, tolerate) {
    .Call('_gsynth_fe_ad_inter_iter', PACKAGE = 'gsynth', Y, Y0, I, force, mc, r, lambda, tolerate)
}

fe_ad_inter_covar_iter <- function(XX, xxinv, Y, Y0, I, beta0, force, mc, r, lambda, tolerate) {
    .Call('_gsynth_fe_ad_inter_covar_iter', PACKAGE = 'gsynth', XX, xxinv, Y, Y0, I, beta0, force, mc, r, lambda, tolerate)
}

beta_iter <- function(X, xxinv, Y, r, tolerate, beta0) {
    .Call('_gsynth_beta_iter', PACKAGE = 'gsynth', X, xxinv, Y, r, tolerate, beta0)
}

inter_fe <- function(Y, X, r, force, beta0, tol = 1e-5) {
    .Call('_gsynth_inter_fe', PACKAGE = 'gsynth', Y, X, r, force, beta0, tol)
}

inter_fe_ub <- function(Y, Y0, X, I, beta0, r, force, tol = 1e-5) {
    .Call('_gsynth_inter_fe_ub', PACKAGE = 'gsynth', Y, Y0, X, I, beta0, r, force, tol)
}

inter_fe_mc <- function(Y, Y0, X, I, beta0, r, lambda, force, tol = 1e-5) {
    .Call('_gsynth_inter_fe_mc', PACKAGE = 'gsynth', Y, Y0, X, I, beta0, r, lambda, force, tol)
}

